In [1]:
import tensorflow as tf
import numpy as np

2022-05-05 15:02:24.722337: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-05 15:02:24.722378: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [9]:
E = tf.constant(np.random.randint(0,100,size=100))
E

<tf.Tensor: shape=(100,), dtype=int64, numpy=
array([96, 61, 54, 52,  4, 35, 87, 52, 86, 15, 29, 85, 61, 51, 85, 87, 73,
       44, 75, 17, 78, 60, 23, 46, 87, 32, 98, 33, 69, 23, 57, 75, 14, 83,
       72, 88, 41, 90, 90, 45, 94, 42, 87, 69, 39, 64, 26, 87, 31, 46, 83,
       97, 24, 75,  3,  9, 13, 85,  4, 59,  4, 71, 78, 10,  1, 72, 40, 93,
       52, 96, 20, 65,  8, 60, 98, 72, 13, 44, 41, 23, 48, 14, 80, 37, 72,
       59, 43, 12, 53, 86, 24, 64, 26, 78,  6, 74, 56, 61, 13, 47])>

In [10]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [11]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [13]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=53>

In [14]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=5304>

In [20]:
tf.math.reduce_std(tf.cast(E,dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.473467>

In [21]:
tf.math.reduce_variance(tf.cast(E,dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=810.73834>

# find positional maximum and minimum|

In [3]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [5]:
tf.argmax(F) # find position maximum of ubove tensor

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [6]:
# index over where largest value present 
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [7]:
tf.reduce_max(F) == F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

# squeezing a tesor (removing all single dimension )